### ISSUE TITLE
Setup from a Mac?

### ISSUE THREAD

**Issue by therioone** [jglim/gunbound-server#9]
Hello,

Thank you for your contribution with these files. I'm a beginner at coding but I'll take my chances with this. 
I always wanted to setup a GunBound server! 

Quick question: Can I setup and run/host the server from a Mac whilst everything else (like client) runs from a Windows?
Thank you for your patience. :)

**Comment by jglim** [comment]
Hello, 

The project does not have a hard dependency on Windows. As far as I can tell, the only dependencies in [requirements.txt](https://github.com/jglim/gunbound-server/blob/master/GunBoundServer/requirements.txt) that require Windows are from PyInstaller and its descendents, which can be safely removed.

Please bear in mind that this project still requires significant work to get up and running; for experimenting and understanding the game, this project is fine, but for playing with others, Serv2 etc. may be a better alternative.
